name: Compilar y Desplegar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Instalar dependencias
        run: npm install

      - name: Compilar el proyecto
        run: npm run build

      - name: Transferir artefactos de construcción
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist Oscar@201.218.159.18:/D/Oscar/Code/deploy
